[package]
name = "my_parser_kma_group_3_siklenchak"
version = "0.1.0"
edition = "2021"
licence = "MIT"
description = "A brief description"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
peg = "0.8.5"
